name: http_certificate_pinning
description: Https Certificate pinning for Flutter. Checks the equality between the known SHA-1 or SHA-256 fingerprint and the SHA-1 or SHA-256 of the target server.
version: 2.0.5
homepage: https://github.com/diefferson/http_certificate_pinning

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: diefferson.http_certificate_pinning
        pluginClass: HttpCertificatePinningPlugin
      ios:
        pluginClass: HttpCertificatePinningPlugin
